/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_filechooserdialog1 (void);
GtkWidget* create_popup_dialog (void);
GtkWidget* create_aboutdialog1 (void);
GtkWidget* create_dialog1 (void);
