/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *vbox2;
  GtkWidget *menubar1;
  GtkWidget *file_menu_item;
  GtkWidget *file_menu_item_menu;
  GtkWidget *load_menu_item;
  GtkWidget *image60;
  GtkWidget *burn_menu_item;
  GtkWidget *image61;
  GtkWidget *erase_menu_item;
  GtkWidget *image62;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit_menu_item;
  GtkWidget *edit_menu_item;
  GtkWidget *edit_menu_item_menu;
  GtkWidget *copy_menu_item;
  GtkWidget *help_menu_item;
  GtkWidget *help_menu_item_menu;
  GtkWidget *quick_start_menu_item;
  GtkWidget *image63;
  GtkWidget *about_menu_item;
  GtkWidget *image64;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *entry1;
  GtkWidget *hbuttonbox2;
  GtkWidget *load_button;
  GtkWidget *burn_button;
  GtkWidget *erase_button;
  GtkWidget *quit_button;
  GtkWidget *main_progressbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (main_window), "gnuProloadV2.0");
  gtk_window_set_default_size (GTK_WINDOW (main_window), 500, 400);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (main_window), vbox2);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox2), menubar1, FALSE, FALSE, 0);

  file_menu_item = gtk_menu_item_new_with_mnemonic ("_File");
  gtk_widget_show (file_menu_item);
  gtk_container_add (GTK_CONTAINER (menubar1), file_menu_item);

  file_menu_item_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file_menu_item), file_menu_item_menu);

  load_menu_item = gtk_image_menu_item_new_with_mnemonic ("_Load");
  gtk_widget_show (load_menu_item);
  gtk_container_add (GTK_CONTAINER (file_menu_item_menu), load_menu_item);
  gtk_tooltips_set_tip (tooltips, load_menu_item, "Load Hex file to Burn", NULL);

  image60 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image60);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (load_menu_item), image60);

  burn_menu_item = gtk_image_menu_item_new_with_mnemonic ("Burn");
  gtk_widget_show (burn_menu_item);
  gtk_container_add (GTK_CONTAINER (file_menu_item_menu), burn_menu_item);
  gtk_tooltips_set_tip (tooltips, burn_menu_item, "Burn Micro with Loaded Hex file", NULL);

  image61 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image61);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (burn_menu_item), image61);

  erase_menu_item = gtk_image_menu_item_new_with_mnemonic ("Erase");
  gtk_widget_show (erase_menu_item);
  gtk_container_add (GTK_CONTAINER (file_menu_item_menu), erase_menu_item);
  gtk_tooltips_set_tip (tooltips, erase_menu_item, "Erase Micro", NULL);

  image62 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image62);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (erase_menu_item), image62);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (file_menu_item_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit_menu_item = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit_menu_item);
  gtk_container_add (GTK_CONTAINER (file_menu_item_menu), quit_menu_item);

  edit_menu_item = gtk_menu_item_new_with_mnemonic ("_Edit");
  gtk_widget_show (edit_menu_item);
  gtk_container_add (GTK_CONTAINER (menubar1), edit_menu_item);

  edit_menu_item_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (edit_menu_item), edit_menu_item_menu);

  copy_menu_item = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy_menu_item);
  gtk_container_add (GTK_CONTAINER (edit_menu_item_menu), copy_menu_item);

  help_menu_item = gtk_menu_item_new_with_mnemonic ("_Help");
  gtk_widget_show (help_menu_item);
  gtk_container_add (GTK_CONTAINER (menubar1), help_menu_item);

  help_menu_item_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menu_item), help_menu_item_menu);

  quick_start_menu_item = gtk_image_menu_item_new_with_mnemonic ("_QuickStart");
  gtk_widget_show (quick_start_menu_item);
  gtk_container_add (GTK_CONTAINER (help_menu_item_menu), quick_start_menu_item);

  image63 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image63);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (quick_start_menu_item), image63);

  about_menu_item = gtk_image_menu_item_new_with_mnemonic ("_About");
  gtk_widget_show (about_menu_item);
  gtk_container_add (GTK_CONTAINER (help_menu_item_menu), about_menu_item);

  image64 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image64);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (about_menu_item), image64);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_end (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_ETCHED_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);
  gtk_container_set_border_width (GTK_CONTAINER (textview1), 10);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, FALSE, FALSE, 0);

  label1 = gtk_label_new ("Enter filename:");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);
  gtk_label_set_line_wrap (GTK_LABEL (label1), TRUE);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox1), entry1, TRUE, TRUE, 0);
  gtk_entry_set_width_chars (GTK_ENTRY (entry1), 35);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (hbox1), hbuttonbox2, TRUE, TRUE, 4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox2), GTK_BUTTONBOX_START);

  load_button = gtk_button_new_with_mnemonic ("Load");
  gtk_widget_show (load_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), load_button);
  GTK_WIDGET_SET_FLAGS (load_button, GTK_CAN_DEFAULT);

  burn_button = gtk_button_new_with_mnemonic ("Burn");
  gtk_widget_show (burn_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), burn_button);
  GTK_WIDGET_SET_FLAGS (burn_button, GTK_CAN_DEFAULT);

  erase_button = gtk_button_new_with_mnemonic ("Erase");
  gtk_widget_show (erase_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), erase_button);
  GTK_WIDGET_SET_FLAGS (erase_button, GTK_CAN_DEFAULT);

  quit_button = gtk_button_new_with_mnemonic ("Quit");
  gtk_widget_show (quit_button);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), quit_button);
  GTK_WIDGET_SET_FLAGS (quit_button, GTK_CAN_DEFAULT);

  main_progressbar = gtk_progress_bar_new ();
  gtk_widget_show (main_progressbar);
  gtk_box_pack_start (GTK_BOX (vbox2), main_progressbar, FALSE, FALSE, 0);
  gtk_progress_bar_set_ellipsize (GTK_PROGRESS_BAR (main_progressbar), PANGO_ELLIPSIZE_END);

  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (on_main_window_delete_event),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy",
                    G_CALLBACK (on_main_window_destroy),
                    NULL);
  g_signal_connect ((gpointer) load_menu_item, "activate",
                    G_CALLBACK (on_load1_activate),
                    NULL);
  g_signal_connect ((gpointer) burn_menu_item, "activate",
                    G_CALLBACK (on_burn1_activate),
                    NULL);
  g_signal_connect ((gpointer) erase_menu_item, "activate",
                    G_CALLBACK (on_erase1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit_menu_item, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy_menu_item, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) quick_start_menu_item, "activate",
                    G_CALLBACK (on_quick_start1_activate),
                    NULL);
  g_signal_connect ((gpointer) about_menu_item, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) load_button, "clicked",
                    G_CALLBACK (on_load_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) burn_button, "clicked",
                    G_CALLBACK (on_burn_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) erase_button, "clicked",
                    G_CALLBACK (on_erase_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) quit_button, "clicked",
                    G_CALLBACK (on_quit_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (main_window, file_menu_item, "file_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, file_menu_item_menu, "file_menu_item_menu");
  GLADE_HOOKUP_OBJECT (main_window, load_menu_item, "load_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, image60, "image60");
  GLADE_HOOKUP_OBJECT (main_window, burn_menu_item, "burn_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, image61, "image61");
  GLADE_HOOKUP_OBJECT (main_window, erase_menu_item, "erase_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, image62, "image62");
  GLADE_HOOKUP_OBJECT (main_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (main_window, quit_menu_item, "quit_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, edit_menu_item, "edit_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, edit_menu_item_menu, "edit_menu_item_menu");
  GLADE_HOOKUP_OBJECT (main_window, copy_menu_item, "copy_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, help_menu_item, "help_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, help_menu_item_menu, "help_menu_item_menu");
  GLADE_HOOKUP_OBJECT (main_window, quick_start_menu_item, "quick_start_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, image63, "image63");
  GLADE_HOOKUP_OBJECT (main_window, about_menu_item, "about_menu_item");
  GLADE_HOOKUP_OBJECT (main_window, image64, "image64");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (main_window, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (main_window, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (main_window, hbuttonbox2, "hbuttonbox2");
  GLADE_HOOKUP_OBJECT (main_window, load_button, "load_button");
  GLADE_HOOKUP_OBJECT (main_window, burn_button, "burn_button");
  GLADE_HOOKUP_OBJECT (main_window, erase_button, "erase_button");
  GLADE_HOOKUP_OBJECT (main_window, quit_button, "quit_button");
  GLADE_HOOKUP_OBJECT (main_window, main_progressbar, "main_progressbar");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *filechooser_cancel;
  GtkWidget *filechooser_open;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("Select File to Burn", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog1), 10);
  gtk_window_set_position (GTK_WINDOW (filechooserdialog1), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (filechooserdialog1), TRUE);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  filechooser_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (filechooser_cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), filechooser_cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (filechooser_cancel, GTK_CAN_DEFAULT);

  filechooser_open = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (filechooser_open);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), filechooser_open, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (filechooser_open, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) filechooserdialog1, "delete_event",
                    G_CALLBACK (on_filechooserdialog1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) filechooserdialog1, "destroy",
                    G_CALLBACK (on_filechooserdialog1_destroy),
                    NULL);
  g_signal_connect ((gpointer) filechooser_cancel, "clicked",
                    G_CALLBACK (on_filechooser_cancel_clicked),
                    NULL);
  g_signal_connect ((gpointer) filechooser_open, "clicked",
                    G_CALLBACK (on_filechooser_open_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, filechooser_cancel, "filechooser_cancel");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, filechooser_open, "filechooser_open");

  gtk_widget_grab_default (filechooser_open);
  return filechooserdialog1;
}

GtkWidget*
create_popup_dialog (void)
{
  GtkWidget *popup_dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *error_label;
  GtkWidget *dialog_action_area2;
  GtkWidget *error_ok_button;

  popup_dialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (popup_dialog), "Error!");
  gtk_window_set_modal (GTK_WINDOW (popup_dialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (popup_dialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_window_set_gravity (GTK_WINDOW (popup_dialog), GDK_GRAVITY_CENTER);

  dialog_vbox2 = GTK_DIALOG (popup_dialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  error_label = gtk_label_new ("");
  gtk_widget_show (error_label);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), error_label, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (popup_dialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_SPREAD);

  error_ok_button = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (error_ok_button);
  gtk_dialog_add_action_widget (GTK_DIALOG (popup_dialog), error_ok_button, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (error_ok_button, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) popup_dialog, "delete_event",
                    G_CALLBACK (on_popup_dialog_delete_event),
                    NULL);
  g_signal_connect ((gpointer) popup_dialog, "destroy",
                    G_CALLBACK (on_popup_dialog_destroy),
                    NULL);
  g_signal_connect ((gpointer) error_ok_button, "clicked",
                    G_CALLBACK (on_error_ok_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (popup_dialog, popup_dialog, "popup_dialog");
  GLADE_HOOKUP_OBJECT_NO_REF (popup_dialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (popup_dialog, error_label, "error_label");
  GLADE_HOOKUP_OBJECT_NO_REF (popup_dialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (popup_dialog, error_ok_button, "error_ok_button");

  return popup_dialog;
}

GtkWidget*
create_aboutdialog1 (void)
{
  GtkWidget *aboutdialog1;
  const gchar *authors[] = {
    "Seemanta Dutta<seemanta@gmail.com> with",
    "help from www.gtkforums.com and the ",
    "gtk-apps-devel-list mailing list.",
    NULL
  };

  aboutdialog1 = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (aboutdialog1), 5);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (aboutdialog1), TRUE);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog1), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog1), "gnuProload");
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog1), "(c) Seemanta Dutta, 2008");
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog1), "Burns AT89S52 based micros in Linux!");
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutdialog1), "This software is licensed under the GNU GENERAL PUBLIC\nLICENSE Version 2 and provided WITHOUT ANY WARRANTY.\n For details, please see the file 'COPYING' that came with its source code.");
  gtk_about_dialog_set_wrap_license (GTK_ABOUT_DIALOG (aboutdialog1), TRUE);
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog1), authors);

  g_signal_connect ((gpointer) aboutdialog1, "response",
                    G_CALLBACK (on_aboutdialog1_response),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog1, aboutdialog1, "aboutdialog1");

  return aboutdialog1;
}

GtkWidget*
create_dialog1 (void)
{
  GtkWidget *dialog1;
  GtkWidget *dialog_vbox3;
  GtkWidget *scrolledwindow2;
  GtkWidget *textview2;
  GtkWidget *dialog_action_area3;
  GtkWidget *okbutton1;

  dialog1 = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog1), "QuickStart Guide");
  gtk_window_set_default_size (GTK_WINDOW (dialog1), 400, 300);
  gtk_window_set_type_hint (GTK_WINDOW (dialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (dialog1)->vbox;
  gtk_widget_show (dialog_vbox3);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  textview2 = gtk_text_view_new ();
  gtk_widget_show (textview2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), textview2);
  gtk_container_set_border_width (GTK_CONTAINER (textview2), 5);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview2), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview2), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview2), FALSE);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview2)), "QuickStart Steps:\n=============\n\n1. Click the Load Button. File chooser dialog will pop-up.\n\n2. Select the Hex file to burn. File should be\nin Intel Hex file format, else you would \nget another error in step 4.\n\n3. Make sure the ICSP board is connected to \nPC COM port and powered ON.\n\n4. Click on 'Burn' to program the microcontroller.", -1);

  dialog_action_area3 = GTK_DIALOG (dialog1)->action_area;
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_SPREAD);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog1), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) dialog1, "delete_event",
                    G_CALLBACK (on_dialog1_delete_event),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog1, "dialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (dialog1, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (dialog1, textview2, "textview2");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog1, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (dialog1, okbutton1, "okbutton1");

  return dialog1;
}

