/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <glib.h>
#include <gtk/gtk.h>


#include "interface.h"
#include "support.h"

#define G_ERRORCHECK_MUTEXES

/* This is where our logo is defined as raw C-source */
extern const guint8 my_pixbuf[];

/* A global variable to enable us to access the main window when we are not
 * in its in 'tree'
 */
GtkWidget *gmain_window_ptr = NULL;

int
main (int argc, char *argv[])
{
  GtkWidget *window1 = NULL;
  GtkWidget *textview_widget = NULL;
  GdkPixbuf *pixbuf = NULL;	
  PangoFontDescription *font = NULL;	
  gtk_set_locale ();
  gtk_init (&argc, &argv);
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_main_window();
  gmain_window_ptr = window1;
  /* Set icon for main window here */
  pixbuf = gdk_pixbuf_new_from_inline (-1, my_pixbuf, FALSE, NULL);	
  gtk_window_set_icon(GTK_WINDOW(gmain_window_ptr), pixbuf);	
  font = pango_font_description_from_string("Monospace Italic 10");
  textview_widget = lookup_widget(gmain_window_ptr, "textview1");
  gtk_widget_modify_font(textview_widget, font);
	
  gtk_widget_show(window1);
  
  gtk_main();
  return 0;
}
